services:
  postgres_nest:
    container_name: postgres_nest
    image: postgres:16-alpine
    restart: always
    ports:
      - "${BD_PORT}:5432"
    environment:
      POSTGRES_DB: ${BD_DATABASE}
      POSTGRES_USER: ${BD_USERNAME}
      POSTGRES_PASSWORD: ${BD_PASSWORD}
    volumes:
      - pg_data_nest:/var/lib/postgresql/data

volumes: 
  pg_data_nest: