services:
  postgres_nest:
    container_name: postgres_nest
    image: postgres:16-alpine
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data_nest:/var/lib/postgresql/data

volumes: 
  pg_data_nest: